# Generated by Django 5.0.6 on 2024-07-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadernocomunicados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
