# Generated by Django 5.0.6 on 2024-07-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadernocomunicados', '0002_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='vista',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
