# Generated by Django 5.0.6 on 2024-07-04 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuadernocomunicados', '0004_ciclolectivo_curso_cursomateria_materia_preceptor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='curso',
        ),
    ]
